version: '3.8'

services:
  dash:
    build:
      context: ./src/main
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: linux/amd64
    ports:
      - "8050:8050"
    platform: linux/amd64
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres_data: { }